name: Testing

on:
  push:
    branches:
    - issue-*
    - milestone-*
    - project-*

jobs:
  Test-0000:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Git User
      run: git config --global user.name "Matt S Trout"
    - name: Setup Git Email
      run: git config --global user.email "mstrout@cpan.org"
    - name: Install Perlbrew
      run: sudo apt install -y perlbrew
    - name: Initial Perlbrew
      run: sudo perlbrew init
    - name: Install CPANM
      run: sudo perlbrew install-cpanm
    - name: Install Perl 5.30
      run: sudo perlbrew install -n perl-5.30.0
    - name: Verify Perl Version
      run: sudo perlbrew exec --with perl-5.30.0 perl -V
    - name: Install Perl::Critic
      run: sudo perlbrew exec --with perl-5.30.0 cpanm -qn Perl::Critic
    - name: Install Perl Dependencies
      run: sudo perlbrew exec --with perl-5.30.0 cpanm -qn --reinstall --installdeps .
    - name: Critiquing Project
      run: sudo perlbrew exec --with perl-5.30.0 perlcritic lib t
    - name: Testing Project
      run: sudo perlbrew exec --with perl-5.30.0 prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9
